SEED = 456
BAND = 'r'
IMAGE_PATH = '../../../data/image_sets_v3'
HOST_PATH = '../../../data/host_info_r5'
MAG_PATH = '../../../data/mag_sets_v4'
OUTPUT_PATH = '../lasair_20240105/'
CUSTOM_TEST_PATH = '../lasair_20240105/test_obj_easy.json'
MODEL_NAME = '_model_test_'
LABEL_PATH =  OUTPUT_PATH + 'label_dict_equal_test.json'
QUALITY_MODEL_PATH = '../bogus_model_without_zscale'
NO_DIFF = True
ONLY_COMPLETE = True
ADD_HOST = True
NEURONS = [[128,3],[64,3]]
RES_CNN_GROUP = None
BATCH_SIZE = 128
EPOCH = 300
LEARNING_RATE = 5e-5